Version: 3
 services:
    web:
	build:
		context: ./php/online-shopping-system
		dockerfile: Dockerfile
	container_name: my_app
	volumes:
		- ./php/online-shopping-system: /var/www/html/
	depends_on:
		- db
	ports:
		8080:80
    db:
	container_name: mysqli
	image: msqli:latest
	command: --default-authentication-plugin=mysql_native_password
	restart: always
	volumes:
		- ./php/online-shopping-system/database/onlineshop.sql: /docker-entrypoint-initdb.d/onlineshop.sql
	environment:
		MYSQL_ROOT_PASSWORD:root
		MYSQL_DATABASE: database
		MYSQL_USER: ezekiel
		MYSQL_PASSWORD: admin
	ports:
		- 3970:3306
